version: '3.8'

services:
  wa-finance-bot:
    build: .
    restart: always
    shm_size: '1g'
    volumes:
      - ./auth_session:/.wwebjs_auth
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS="--dns-result-order=ipv4first"
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    deploy:
      resources:
        limits:
          memory: 512M
